{
	"data": "ENC[AES256_GCM,data:zref3lUbFNAXE2Wd8Sr9IyP4EicfZun8raAQMcI+dqC8nyniXRfwbLU72LJiHzzMYE5K2WYBlAlFXRJp6TM3zbv7kytqjm1Xi4LKbNkeSTkvk6Mnaz+Kr1rlk6xftNggj36X3sbmKk3XJDC4h2sQLwMo/evuKT3Od5xN43AzhhcvRNto5NrIWSIxzqL2HZXjVG1kWL8849f7xNxdxZvGhapfdwUTpGTHmo8RLHeKKJzPECB9g8LRVruITeTTSmxxrdie2lJLZHSJ4ZXN5pvdwULoEOqpg6q5Y8LgcRea/gz3+jzxdvkoJHkTx6/rygVPNsQZ0fL0L+5NThxLP/gn1IgrNSQ0wRE+DA6bo+k3jSXXgE/sLr/BvImJvlgcaW+zW/VYzN8IbtU5r+uT2g1GWc1q2PwhrGiciX9Gf9CusSd3c44dHmP+HbYeEwvC60QdFohxqILEdnc59iJRLhc2jYHpXztQPQa4+3qqztUK0UQGuGF8o9vmW8Kze7lRKbwy4rtal4XlIYpS55wZB4/DcJ1SJf7a+RASvNRA5lRdylXN3OzJis0S1JngdDNHvfFaDGFerXH1dBdIu9FXoEJZzv5akUr+W8fo5jRr7gKtt6b4RIbBrDYQbH0hp9CFIK0yv6gL82Ih,iv:PtBir0nVNo7m6i2TZzY/5cA2vzpa4EY2uIEEJKGi+u0=,tag:fvHRo/6MpY9FJ+N9RBGzCw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVXFLVUNxYUxZRHIvendH\nbEVRUVJxa3lJc2ZDSHpYM2h1Wlc1L2FHTVRZCmRhSk5SMEg4TTg0c0NxenZoVnlx\nSVd4ODRDZGkvelczbTVDUzI2YThVZjQKLS0tIElxWlNMdkwzbGdxeWd4WGtvZDJJ\nK3kzOXdOK2pWN0lVL0wxRUkwVldQUEUKeLoTlewz6PD+tKjWWIhIoZDfELGZtb3V\nDNGZqL3H/FsJw3dhpPfbDl3ZkvkE00VPZV2ORkxQSCGaA/f17AGbTw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c"
			}
		],
		"lastmodified": "2026-06-12T04:59:36Z",
		"mac": "ENC[AES256_GCM,data:lnyBtC60kTnjpTvEnqtm8ejPG8ZtrPg0aefSc8365e4Ma/CYaFlIufOL2S+g1GGwV/HzZyIwjxJPqFV724d/SA2uNr9FwrRIsgFL0zOeTwrxr3WDU5reXaOFEnFNoSue1qP+7EBVcpOy+vAi3lKB6/8qxfD3rM0Fcm+1bEmwI/g=,iv:PpLY+jneXsk+DeTI30awCoRWMcrz59YfelAlRRMxmrU=,tag:IaMoIxElyEcbgx3yRm9z0A==,type:str]",
		"version": "3.13.1"
	}
}
