{
	"data": "ENC[AES256_GCM,data:idnpD7kwEdCM1EK1zq8nwC3bhsoBQk/S8dSeOvZiAzWM2IU9OSUX28tMwN4DPycbkRvl7DepuwKIUGGbtSWP6JHjMTkSR5s0yLpmhaDJ+5V3IBl+BpgbDH3vzmHQ7BCer/JgvXvkEdBkIR4ryUvxgccXmI704C7OL4/IMM3tDIilZxH9kaMfOw8Ey3JUQb/+ACHI7ZDYr8FsN1vlxPUPkFD5qYwWveLXlPf3117bc8IA8uFT+qZWM3jspf0=,iv:uiRm+CXqZfOPizcMs22kIi4Huj1vApF0LuIqkOcWjSg=,tag:ZHxskjKuFLlfctqq1ffl7w==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeXJnaVZLUjgxaXpnTjl2\nZ0JWN2ZLNWJCUGpPcjE3N2hFb2VFemNYQ0JJCjFTOU5ZT2tsckNEZFZ4d1VjTVFa\nSER0a2w3dXc1Y1ovckxLMDhRai85cFUKLS0tIC96TmpQdE1kVm1QTkMyYkltaTZD\nOXFEQ0M1R2N6T0t2ckM4OG8yVGRiMTQKbVevRwmPYFM0AAKjZQvzPYblS8bIpPyO\nDdvDRuWHNmxaSBu9ORH2ZrsltWh9tmSF9VDgTRXI3aTwBzNfYsxN2A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-12T03:03:46Z",
		"mac": "ENC[AES256_GCM,data:hc04nDDa5PmeNKkbZrnE7uXP1CJEydXb9ZwmDHlTMJfdidJONdA8sMHC4FciLt8nayqYvwqr08Vl5rmXkbITx7b1ZkNCgtuyqYChTr4xxBlM4SNwOty4Hhx0akM1CAoaXY7fToKgZ9T+1qkDp3Z5owPV1bFCqZfMnMsOWWp9mPY=,iv:p5B3CdF0ng2lZ3WwxgNvkvY3SEln0Edj+MbjGqsfPyM=,tag:2UKe7iruLjm1rb5iorsthQ==,type:str]",
		"version": "3.12.2"
	}
}
